name: Periodic health check, hourly

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: health check
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://full-stack-open-2022-osa-11-production.up.railway.app/health
          follow-redirect: false
          max-attempts: 3
          retry-delay: 10s
          retry-all: false
